AA = 123

all: install uninstall clean 1.c  ${AA} clean
	echo "all"
	echo ===================
	echo $@
	echo ===================
	echo $^	
	echo ===================
	echo $+	
	echo ===================
	echo $<	
	echo ===================

install:
	echo "install"

uninstall:
	echo "uninstall"

clean:
	echo "clean"

.PHONY:123
123:
	echo 123
